# Alacritty Config TOML

[shell]
args = ['--login']
program = "/usr/bin/bash"

[cursor]
style.shape = "Beam"
style.blinking = "Always"
blink_interval = 800

[font]
size = 16.0
normal.family = "Hack Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 1.0

padding.x = 0
padding.y = 0

dimensions.columns = 90
dimensions.lines = 25

[colors]
normal.black = "#21222c"
normal.red = "#ff5555"
normal.green = "#50fa7b"
normal.yellow = "#f1fa8c"
normal.blue = "#bd93f9"
normal.magenta = "#ff79c6"
normal.cyan = "#8be9fd"
normal.white = "#f8f8f2"

primary.background = "#000000"
primary.foreground = "#f8f8f2"

cursor.text = "CellBackground"
cursor.cursor = "CellForeground"
